apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-postgresql-credentials
  namespace: shopsphere-data
  annotations:
    shopsphere.io/template-only: "true"
type: Opaque
stringData:
  postgres-password: REPLACE_WITH_STRONG_ADMIN_PASSWORD
  customer-password: REPLACE_WITH_STRONG_CUSTOMER_DATABASE_PASSWORD
  keycloak-password: REPLACE_WITH_STRONG_KEYCLOAK_DATABASE_PASSWORD
  catalogue-password: REPLACE_WITH_STRONG_CATALOGUE_DATABASE_PASSWORD
