apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopsphere-apps

resources:
  - service.yaml
  - deployment.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: order-service
      app.kubernetes.io/component: order-processing
      app.kubernetes.io/part-of: shopsphere
      app.kubernetes.io/managed-by: kustomize
