apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopsphere-data

resources:
  - service.yaml
  - statefulset.yaml
  - network-policy.yaml

configMapGenerator:
  - name: postgresql-initialization
    files:
      - init-databases.sh

generatorOptions:
  disableNameSuffixHash: false
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: shopsphere

labels:
  - pairs:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: shopsphere
      app.kubernetes.io/managed-by: kustomize
