apiVersion: v1
kind: LimitRange
metadata:
  name: shopsphere-apps-container-limits
  namespace: shopsphere-apps
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 25m
        memory: 32Mi
      max:
        cpu: "2"
        memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: shopsphere-data-container-limits
  namespace: shopsphere-data
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      default:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "4"
        memory: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: shopsphere-platform-container-limits
  namespace: shopsphere-platform
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 300m
        memory: 384Mi
      min:
        cpu: 25m
        memory: 32Mi
      max:
        cpu: "1"
        memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: shopsphere-monitoring-container-limits
  namespace: shopsphere-monitoring
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 300m
        memory: 512Mi
      min:
        cpu: 25m
        memory: 32Mi
      max:
        cpu: "1"
        memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: shopsphere-security-container-limits
  namespace: shopsphere-security
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 250m
        memory: 256Mi
      min:
        cpu: 25m
        memory: 32Mi
      max:
        cpu: 750m
        memory: 1Gi
