apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopsphere-apps

resources:
  - ../../../base/catalogue-service

configMapGenerator:
  - name: catalogue-service-environment
    literals:
      - APP_ENV=poc
      - LOG_LEVEL=INFO
      - SERVICE_NAME=catalogue-service
      - SERVICE_VERSION=0.1.0
      - TELEMETRY_ENABLED=true
      - OTEL_SDK_DISABLED=false
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://opentelemetry-collector.shopsphere-monitoring.svc.cluster.local:4318/v1/traces
      - OTEL_EXPORTER_OTLP_TRACES_TIMEOUT=5
      - OTEL_BSP_MAX_QUEUE_SIZE=512
      - OTEL_BSP_MAX_EXPORT_BATCH_SIZE=128
      - OTEL_BSP_SCHEDULE_DELAY=2000
      - OTEL_BSP_EXPORT_TIMEOUT=5000
      - DATABASE_CONNECT_TIMEOUT_SECONDS=3
      - KEYCLOAK_ISSUER=http://localhost:8080/realms/shopsphere
      - KEYCLOAK_AUDIENCE=shopsphere-api
      - KEYCLOAK_ROLE_CLIENT_ID=shopsphere-api
      - KEYCLOAK_JWKS_URL=http://keycloak.shopsphere-platform.svc.cluster.local:8080/realms/shopsphere/protocol/openid-connect/certs
      - JWT_CLOCK_SKEW_SECONDS=30
      - REDIS_URL=redis://redis.shopsphere-data.svc.cluster.local:6379/0
      - REDIS_CONNECT_TIMEOUT_SECONDS=0.5
      - CACHE_KEY_PREFIX=shopsphere:catalogue:v1
      - CATEGORY_CACHE_TTL_SECONDS=300
      - PRODUCT_CACHE_TTL_SECONDS=180
      - SEARCH_CACHE_TTL_SECONDS=60
      - PRICE_CACHE_TTL_SECONDS=120
      - AVAILABILITY_CACHE_TTL_SECONDS=15
      - KAFKA_BOOTSTRAP_SERVERS=kafka.shopsphere-platform.svc.cluster.local:9092
      - KAFKA_CLIENT_ID=catalogue-service-outbox
      - KAFKA_REQUEST_TIMEOUT_MS=5000
      - OUTBOX_POLL_INTERVAL_SECONDS=2
      - OUTBOX_RETRY_BASE_SECONDS=2
      - OUTBOX_BATCH_SIZE=50
      - OUTBOX_LEASE_SECONDS=60

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      shopsphere.io/environment: poc
