apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: shopsphere-monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: telemetry-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
    - name: health
      port: 13133
      targetPort: health
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: metrics
      protocol: TCP
