#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly OUTPUT_FILE="${REPOSITORY_ROOT}/docs/evidence/tool-versions.md"

has_command() {
    command -v "$1" >/dev/null 2>&1
}

first_line() {
    sed -n '1p'
}

simple_version() {
    local command_name="$1"
    shift

    if ! has_command "$command_name"; then
        printf 'Not detected'
        return
    fi

    local output
    output="$("$command_name" "$@" 2>/dev/null | first_line || true)"
    printf '%s' "${output:-Detected; version unavailable}"
}

docker_plugin_version() {
    local plugin="$1"
    if ! has_command docker || ! docker "$plugin" version >/dev/null 2>&1; then
        printf 'Not detected'
        return
    fi

    docker "$plugin" version 2>/dev/null | first_line
}

jenkins_version() {
    if has_command dpkg-query; then
        local package_version
        package_version="$(dpkg-query --show --showformat='${Version}' jenkins 2>/dev/null || true)"
        if [[ -n "$package_version" ]]; then
            printf '%s' "$package_version"
            return
        fi
    fi

    printf 'Not detected'
}

jenkins_state() {
    if ! has_command systemctl; then
        printf 'Unavailable'
        return
    fi

    local state
    state="$(systemctl show jenkins --property=ActiveState --value 2>/dev/null || true)"
    printf '%s' "${state:-Not found}"
}

os_description() {
    if [[ -r /etc/os-release ]]; then
        (
            # shellcheck disable=SC1091
            source /etc/os-release
            printf '%s' "${PRETTY_NAME:-${NAME:-Unknown Linux}}"
        )
    else
        uname -s
    fi
}

main() {
    local generated_at
    generated_at="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

    {
        printf '# Day 1 Tool Versions\n\n'
        printf '> Generated by `scripts/capture-tool-versions.sh` using read-only version queries. No environment variables, credentials, Jenkins secrets, or passwords are captured.\n\n'
        printf -- '- Captured at (UTC): `%s`\n' "$generated_at"
        printf -- '- Host OS: `%s`\n' "$(os_description)"
        printf -- '- Architecture: `%s`\n\n' "$(uname -m)"
        printf '| Tool | Detected version or state |\n'
        printf '| --- | --- |\n'
        printf '| Bash | `%s` |\n' "$(simple_version bash --version)"
        printf '| Git | `%s` |\n' "$(simple_version git --version)"
        printf '| Make | `%s` |\n' "$(simple_version make --version)"
        printf '| Python | `%s` |\n' "$(simple_version python3 --version)"
        printf '| Node.js | `%s` |\n' "$(simple_version node --version)"
        printf '| npm | `%s` |\n' "$(simple_version npm --version)"
        printf '| Docker | `%s` |\n' "$(simple_version docker --version)"
        printf '| Docker Compose | `%s` |\n' "$(docker_plugin_version compose)"
        printf '| Docker Buildx | `%s` |\n' "$(docker_plugin_version buildx)"
        printf '| kubectl | `%s` |\n' "$(simple_version kubectl version --client=true)"
        printf '| kind | `%s` |\n' "$(simple_version kind version)"
        printf '| Terraform | `%s` |\n' "$(simple_version terraform version)"
        printf '| Jenkins package | `%s` |\n' "$(jenkins_version)"
        printf '| Jenkins service | `%s` |\n' "$(jenkins_state)"
        printf '| Java | `%s` |\n' "$(simple_version java --version)"
        printf '| ShellCheck | `%s` |\n' "$(simple_version shellcheck --version)"
    } >"$OUTPUT_FILE"

    printf '[OK] Wrote sanitized tool-version evidence to %s\n' "$OUTPUT_FILE"
}

main "$@"
