#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly OVERLAY="${REPOSITORY_ROOT}/platform/kubernetes/overlays/poc/redis"

fail() {
    printf '[ERROR] %s\n' "$*" >&2
    exit 1
}

require_text() {
    local content="$1"
    local expected="$2"
    grep -Fq -- "$expected" <<<"$content" || fail "Required Redis configuration was not found: ${expected}"
}

main() {
    local rendered=""
    command -v kubectl >/dev/null 2>&1 || fail "Required command 'kubectl' was not found."
    rendered="$(kubectl kustomize "$OVERLAY")"
    [[ -n "$rendered" ]] || fail "Redis overlay rendered no resources."
    grep -Eq '^kind: Secret$' <<<"$rendered" && fail "A Secret must not be generated by the committed overlay."
    grep -Eq '^[[:space:]]+type: (NodePort|LoadBalancer)$' <<<"$rendered" && fail "Redis must be ClusterIP-only."
    require_text "$rendered" "namespace: shopsphere-data"
    require_text "$rendered" "type: ClusterIP"
    require_text "$rendered" "startupProbe:"
    require_text "$rendered" "readinessProbe:"
    require_text "$rendered" "livenessProbe:"
    require_text "$rendered" "readOnlyRootFilesystem: true"
    require_text "$rendered" "runAsNonRoot: true"
    require_text "$rendered" "name: shopsphere-redis-credentials"
    require_text "$rendered" "appendonly no"
    require_text "$rendered" "save \"\""
    require_text "$rendered" "kind: NetworkPolicy"
    printf '%s\n' "$rendered" | kubectl create --dry-run=client --validate=false -f - >/dev/null
    printf '[OK] Redis manifests passed non-destructive validation.\n'
}

main "$@"
