#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly OVERLAY="${REPOSITORY_ROOT}/platform/kubernetes/overlays/poc/customer-service"

fail() {
    printf '[ERROR] %s\n' "$*" >&2
    exit 1
}

require_command() {
    local command_name="$1"
    command -v "$command_name" >/dev/null 2>&1 || fail "Required command '${command_name}' was not found."
}

require_text() {
    local content="$1"
    local expected="$2"
    grep -Fq -- "$expected" <<<"$content" || fail "Required configuration was not found: ${expected}"
}

main() {
    local rendered=""

    require_command kubectl
    rendered="$(kubectl kustomize "$OVERLAY")"
    [[ -n "$rendered" ]] || fail "Customer-service overlay rendered no resources."

    grep -Eq '^kind: Secret$' <<<"$rendered" && fail "A Secret must not be generated by the committed overlay."
    grep -Eq '^[[:space:]]+type: (NodePort|LoadBalancer)$' <<<"$rendered" && \
        fail "customer-service must not use NodePort or LoadBalancer."
    grep -Eqi '(password|secret)[[:space:]]*:[[:space:]]*(admin|password|change.?me)' <<<"$rendered" && \
        fail "A credential-like literal was found in rendered manifests."

    require_text "$rendered" "namespace: shopsphere-apps"
    require_text "$rendered" "type: ClusterIP"
    require_text "$rendered" "startupProbe:"
    require_text "$rendered" "path: /health/ready"
    require_text "$rendered" "path: /health/live"
    require_text "$rendered" "readOnlyRootFilesystem: true"
    require_text "$rendered" "runAsNonRoot: true"
    require_text "$rendered" "allowPrivilegeEscalation: false"
    require_text "$rendered" "name: shopsphere-customer-service-database"
    require_text "$rendered" "name: shopsphere-customer-activity-keycloak"
    require_text "$rendered" "kind: NetworkPolicy"
    require_text "$rendered" "app.kubernetes.io/name: api-gateway"
    require_text "$rendered" "type: RollingUpdate"

    printf '%s\n' "$rendered" | kubectl create --dry-run=client --validate=false -f - >/dev/null
    printf '[OK] Customer-service manifests passed non-destructive validation.\n'
}

main "$@"

