#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly OVERLAY="${REPOSITORY_ROOT}/platform/kubernetes/overlays/poc/keycloak"
readonly REALM_FILE="${REPOSITORY_ROOT}/platform/kubernetes/base/keycloak/realm/shopsphere-realm.json"
readonly POLICY_PROFILES_FILE="${REPOSITORY_ROOT}/platform/kubernetes/base/keycloak/client-policies/profiles.json"
readonly POLICIES_FILE="${REPOSITORY_ROOT}/platform/kubernetes/base/keycloak/client-policies/policies.json"

fail() {
    printf '[ERROR] %s\n' "$*" >&2
    exit 1
}

require_command() {
    local command_name="$1"
    command -v "$command_name" >/dev/null 2>&1 || fail "Required command '${command_name}' was not found."
}

require_text() {
    local content="$1"
    local expected="$2"
    grep -Fq -- "$expected" <<<"$content" || fail "Required configuration was not found: ${expected}"
}

main() {
    local rendered=""
    local realm=""

    require_command kubectl
    require_command python3
    [[ -r "$REALM_FILE" ]] || fail "Realm configuration was not found: ${REALM_FILE}"
    [[ -r "$POLICY_PROFILES_FILE" ]] || fail "Client-policy profiles were not found: ${POLICY_PROFILES_FILE}"
    [[ -r "$POLICIES_FILE" ]] || fail "Client policies were not found: ${POLICIES_FILE}"

    python3 -m json.tool "$REALM_FILE" >/dev/null
    python3 -m json.tool "$POLICY_PROFILES_FILE" >/dev/null
    python3 -m json.tool "$POLICIES_FILE" >/dev/null

    rendered="$(kubectl kustomize "$OVERLAY")"
    realm="$(<"$REALM_FILE")"
    [[ -n "$rendered" ]] || fail "Keycloak overlay rendered no resources."

    grep -Eq '^kind: Secret$' <<<"$rendered" && fail "A Secret must not be generated by the committed overlay."
    grep -Eq '^[[:space:]]+type: (NodePort|LoadBalancer)$' <<<"$rendered" && \
        fail "Keycloak must not use NodePort or LoadBalancer."
    grep -Eqi '(password|secret)[[:space:]]*:[[:space:]]*(admin|password|change.?me)' <<<"$rendered" && \
        fail "A credential-like literal was found in rendered manifests."

    require_text "$rendered" "namespace: shopsphere-platform"
    require_text "$rendered" "type: ClusterIP"
    require_text "$rendered" "startupProbe:"
    require_text "$rendered" "readinessProbe:"
    require_text "$rendered" "livenessProbe:"
    require_text "$rendered" "postgresql.shopsphere-data.svc.cluster.local:5432/keycloak_db"
    require_text "$rendered" "quay.io/keycloak/keycloak:26.7.0"

    require_text "$realm" '"realm": "shopsphere"'
    require_text "$realm" '"name": "customer"'
    require_text "$realm" '"name": "support"'
    require_text "$realm" '"name": "operations_admin"'
    require_text "$realm" '"clientId": "shopsphere-frontend"'
    require_text "$realm" '"publicClient": true'
    require_text "$realm" '"standardFlowEnabled": true'
    require_text "$realm" '"implicitFlowEnabled": false'
    require_text "$realm" '"registrationAllowed": true'
    require_text "$realm" '"bruteForceProtected": true'
    require_text "$realm" '"eventsEnabled": true'
    require_text "$realm" '"adminEventsEnabled": true'
    require_text "$realm" '"adminEventsDetailsEnabled": false'
    require_text "$realm" '"clientId": "shopsphere-customer-activity-reader"'
    require_text "$realm" '"UPDATE_PROFILE"'
    require_text "$realm" '"UPDATE_EMAIL"'
    require_text "$realm" '${SHOPSPHERE_FRONTEND_BASE_URL}'
    require_text "$(<"$POLICY_PROFILES_FILE")" '"executor": "pkce-enforcer"'
    require_text "$(<"$POLICIES_FILE")" '"profiles": ['
    require_text "$(<"$POLICIES_FILE")" '"shopsphere-pkce-s256"'

    printf '%s\n' "$rendered" | kubectl create --dry-run=client --validate=false -f - >/dev/null
    printf '[OK] Keycloak manifests and sanitized realm configuration passed non-destructive validation.\n'
}

main "$@"
