#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly OVERLAY="${REPOSITORY_ROOT}/platform/kubernetes/overlays/poc/postgresql"

fail() {
    printf '[ERROR] %s\n' "$*" >&2
    exit 1
}

require_command() {
    local command_name="$1"
    command -v "$command_name" >/dev/null 2>&1 || fail "Required command '${command_name}' was not found."
}

require_text() {
    local rendered="$1"
    local expected="$2"
    grep -Fq -- "$expected" <<<"$rendered" || fail "Rendered manifests do not contain required text: ${expected}"
}

main() {
    local rendered=""

    require_command kubectl
    [[ -r "${OVERLAY}/kustomization.yaml" ]] || fail "PostgreSQL overlay was not found: ${OVERLAY}"

    rendered="$(kubectl kustomize "$OVERLAY")"
    [[ -n "$rendered" ]] || fail "PostgreSQL overlay rendered no resources."

    grep -Eq '^kind: Secret$' <<<"$rendered" && fail "A Secret must not be generated by the committed overlay."
    grep -Eq '^[[:space:]]+type: (NodePort|LoadBalancer)$' <<<"$rendered" && \
        fail "PostgreSQL must not use NodePort or LoadBalancer."

    require_text "$rendered" "namespace: shopsphere-data"
    require_text "$rendered" "type: ClusterIP"
    require_text "$rendered" "kind: StatefulSet"
    require_text "$rendered" "startupProbe:"
    require_text "$rendered" "readinessProbe:"
    require_text "$rendered" "livenessProbe:"
    require_text "$rendered" "volumeClaimTemplates:"
    require_text "$rendered" "storage: 80Gi"
    require_text "$rendered" "customer_db"
    require_text "$rendered" "keycloak_db"
    require_text "$rendered" "catalogue_db"
    require_text "$rendered" "key: catalogue-password"
    require_text "$rendered" "order_db"
    require_text "$rendered" "order_app"
    require_text "$rendered" "key: order-password"
    require_text "$rendered" "requests:"
    require_text "$rendered" "limits:"

    printf '%s\n' "$rendered" | kubectl create --dry-run=client --validate=false -f - >/dev/null
    printf '[OK] PostgreSQL manifests rendered and passed non-destructive client validation.\n'
}

main "$@"
