#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
readonly OVERLAY="${REPOSITORY_ROOT}/platform/kubernetes/overlays/poc/order-service"

fail() {
    printf '[ERROR] %s\n' "$*" >&2
    exit 1
}

require_text() {
    local content="$1"
    local expected="$2"
    grep -Fq -- "$expected" <<<"$content" || \
        fail "Required order-service configuration was not found: ${expected}"
}

main() {
    local rendered=""
    command -v kubectl >/dev/null 2>&1 || fail "Required command 'kubectl' was not found."
    rendered="$(kubectl kustomize "$OVERLAY")"
    [[ -n "$rendered" ]] || fail "Order-service overlay rendered no resources."
    grep -Eq '^kind: Secret$' <<<"$rendered" && \
        fail "A Secret must not be generated by the committed overlay."
    grep -Eq '^[[:space:]]+type: (NodePort|LoadBalancer)$' <<<"$rendered" && \
        fail "order-service must be ClusterIP-only."
    require_text "$rendered" "namespace: shopsphere-apps"
    require_text "$rendered" "type: ClusterIP"
    require_text "$rendered" "name: shopsphere-order-service-database"
    require_text "$rendered" "name: shopsphere-order-service-identity"
    require_text "$rendered" "CATALOGUE_SERVICE_URL: http://catalogue-service.shopsphere-apps.svc.cluster.local:8000/api/v1"
    require_text "$rendered" "KAFKA_BOOTSTRAP_SERVERS: kafka.shopsphere-platform.svc.cluster.local:9092"
    require_text "$rendered" "path: /health/ready"
    require_text "$rendered" "path: /health/live"
    require_text "$rendered" "readOnlyRootFilesystem: true"
    require_text "$rendered" "runAsNonRoot: true"
    require_text "$rendered" "kind: NetworkPolicy"
    require_text "$rendered" "type: RollingUpdate"
    require_text "$rendered" "terminationGracePeriodSeconds: 45"
    printf '%s\n' "$rendered" | \
        kubectl create --dry-run=client --validate=false -f - >/dev/null
    printf '[OK] Order-service manifests passed non-destructive validation.\n'
}

main "$@"
