apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopsphere-apps

resources:
  - ../../../base/api-gateway

configMapGenerator:
  - name: api-gateway-environment
    literals:
      - APP_ENV=poc
      - LOG_LEVEL=INFO
      - SERVICE_NAME=api-gateway
      - SERVICE_VERSION=0.1.0
      - TELEMETRY_ENABLED=true
      - OTEL_SDK_DISABLED=false
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://opentelemetry-collector.shopsphere-monitoring.svc.cluster.local:4318/v1/traces
      - OTEL_EXPORTER_OTLP_TRACES_TIMEOUT=5
      - OTEL_BSP_MAX_QUEUE_SIZE=512
      - OTEL_BSP_MAX_EXPORT_BATCH_SIZE=128
      - OTEL_BSP_SCHEDULE_DELAY=2000
      - OTEL_BSP_EXPORT_TIMEOUT=5000
      - CUSTOMER_SERVICE_URL=http://customer-service.shopsphere-apps.svc.cluster.local:8000
      - CUSTOMER_SERVICE_TIMEOUT_SECONDS=5
      - CATALOGUE_SERVICE_URL=http://catalogue-service.shopsphere-apps.svc.cluster.local:8000
      - CATALOGUE_SERVICE_TIMEOUT_SECONDS=5
      - ORDER_SERVICE_URL=http://order-service.shopsphere-apps.svc.cluster.local:8000
      - ORDER_SERVICE_TIMEOUT_SECONDS=10
      - CORS_ALLOWED_ORIGINS=http://localhost:5173

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      shopsphere.io/environment: poc
