apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopsphere-platform

resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml

configMapGenerator:
  - name: keycloak-realm-import
    files:
      - shopsphere-realm.json=realm/shopsphere-realm.json
      - client-policy-profiles.json=client-policies/profiles.json
      - client-policies.json=client-policies/policies.json

generatorOptions:
  disableNameSuffixHash: false
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: shopsphere

labels:
  - pairs:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/component: identity-provider
      app.kubernetes.io/part-of: shopsphere
      app.kubernetes.io/managed-by: kustomize
