apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-ingress
  namespace: shopsphere-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/component: identity-provider
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              shopsphere.io/tier: applications
        - namespaceSelector:
            matchLabels:
              shopsphere.io/tier: platform
      ports:
        - protocol: TCP
          port: 8080
