apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: shopsphere-apps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalogue-service
    app.kubernetes.io/component: catalogue-inventory
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
