apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-manager
  namespace: shopsphere-security
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: wazuh-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wazuh-manager
    spec:
      enableServiceLinks: false
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.14.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1514
              name: agent-events
              protocol: TCP
            - containerPort: 1515
              name: agent-enroll
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: ossec-api-config
              mountPath: /var/ossec/api/configuration
            - name: ossec-etc
              mountPath: /var/ossec/etc
            - name: ossec-logs
              mountPath: /var/ossec/logs
      volumes:
        - name: ossec-api-config
          emptyDir: {}
        - name: ossec-etc
          emptyDir: {}
        - name: ossec-logs
          emptyDir: {}
